language: node_js
node_js:
  - 8.9.4
branches:
  only:
    - master
    - dev
before_script:
  - npm install -g ionic cordova jest
script:
  - npm run test-ci
deploy:
  provider: heroku
  api_key:
    secure: DESSnd3OZehSaQnvIyuD6vDEYqJJfakAuHl6RpfYO7rfsVx5ebiaju3CAd2f/J4AUv6lwPjjffsYiUGn7GfO35/6K2cQMIO2jZ4K80RR6SCFNGIdWnaNpCAVYHr1d3PuzJ9aeZSditFIKkp
  app: my-reboot
  on:
    repo: phortonssf/reboot
