language: node_js
node_js:
  - 8.9.4
branches:
  only:
    - master
    - dev
before_script:
  - npm install -g ionic cordova jest
script:
  - npm run test-ci
deploy:
  provider: heroku
  api_key:
    secure: "DESSnd3OZehSaQnvIyuD6vDEYqJJfakAuHl6RpfYO7rfsVx5ebiaju3CAd2f/J4AUv6lwPjjffsY9ALJ4zQHVu6adaVV9n8RGtpM/qfC7Lhp5u80Y65D92jT1aNB35A2y4fLLmnC73vjSiFiUGn7GfO35/6K2cQMIO2jZ4K80RR6SCFNGIdWnaNpCAVYHr1d3PuzJ9aeZSditFIKkpaMYhtXg5dGZvCiTdAt6nc+6oycu4jdCll48jchxkGGx8mbzMW6aOUwr0+f6ag+2TjWAJlt9/k8i07ZLdF9U0lbQCSy1eAcCkqtQcfevHW5IiaCKjMC6kQ1XpS9mJWuzQbuV+iiOyxArmKcdUjF7aa1xQ+GKPWoy12oruoaR+8rTQQZqFrTKkFv2C4bq8PgzOIzXNIG3b163LvM/XCs6OvVD7RkafMYaqYUs5Sp94FDA+BpEaJO58tUyUMFmRinjiT3CS+B3zWSuewIfhG7M6Tg7u3sBunWx9fK+Kdf29t1XOghQQJ6oJhYm8xhTPfVmzMma2g5jMi0tyW9HyJ3S7UcdtRNnB1i8OjP6VtktsA5DnBUvi68og7ZMKLkz7qC9WfJUP4/ih1HANHQonaT5cQg4FVqlgvrNZNxSlawR25md6Dpx0FPRRRbsKerYrRQrYk2AZQul/glBoFL6tfSbu4/svg="
  app: my-reboot
  on:
    repo: phortonssf/reboot
