language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master
    - dev

before_script:
  - npm install -g ionic cordova jest

script:
  - npm run test-ci

deploy:
  provider: heroku
  api_key:
    - secure: 4bad570d-18ad-415c-b2ac-d5c3265fab01
  app: my-reboot
  on:
    repo: phortonssf/reboot
